---
language: python
services: docker

env:
  global:
    - ROLE_NAME: docker
  matrix:
    - MOLECULE_DISTRO: centos7
      MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd
    - MOLECULE_DISTRO: ubuntu1804
install:
  # Install test dependencies.
  - pip install molecule 

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME pytool.$ROLE_NAME
  - cd pytool.$ROLE_NAME

script:
  # Run tests.
  - true

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
