---
- name: Create docker group
  group:
    name: "{{docker_group}}"
    gid: "{{docker_gid}}"
    state: present
  ignore_errors: true
  tags:
    - docker

- name: Create docker user
  user:
    name: "{{docker_user}}"
    uid: "{{docker_uid}}"
    group: "{{docker_group}}"
    shell: /usr/sbin/nologin
    comment: "Docker user"
    system: yes
  ignore_errors: true
  when:
    - docker_user | bool
  tags: docker

- name:  Add {{docker_user}} user to docker group.
  ignore_errors: true
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"
