---
- include_tasks: docker-clean.yml
  tags: [ 'never', 'clean' ]

- include_tasks: docker-users.yml
  when: docker_users

- name: Create docker directory (used to store archives)
  file: name={{ item }} state=directory
  with_items:
    - "/etc/docker/"
    - "{{ docker_bin_dir }}"
    - "{{ docker_data_dir }}"
    - "{{ docker_download_dir }}"
  tags: docker

# - name: Check docker packages file exists
#   stat:
#     path: "{{docker_download_dir}}/docker-${docker_version}.tgz"
#   register: package

# get_url checksum 正确不在重新下载
- name: Downloading official Docker binaries archive
  become: no
  delegate_to: localhost
  get_url:
    url: "{{docker_download_url}}"
    dest: "{{ docker_download_dir }}/docker-{{docker_version}}.tgz"
    checksum: "sha256:{{ docker_checksum_sha256.split(' ')|first }}"
    mode: 0755
    timeout: 42
  run_once: true
  tags: [docker,down,download]

# unarchive creates 文件存在不在重复解压
- name: unarchive downloaded Docker archive
  become: yes
  connection: local
  unarchive:
    src: "{{ docker_download_dir }}/docker-{{docker_version}}.tgz"
    dest: "{{ docker_download_dir }}"
    creates: "{{ docker_download_dir }}/docker/docker"
    # remote_src: yes
  tags: docker

- name: Copy Docker binaries to destination directory
  become: true
  copy:
    src: "{{ docker_download_dir }}/docker/{{item}}"
    dest: "{{docker_bin_dir}}/{{item}}"
    mode: 0755
    owner: root
    group: root
    # remote_src: yes
  with_items:
    - docker
    - dockerd
    - docker-init
    - docker-runc
    - docker-proxy
    - docker-containerd
    - docker-containerd-ctr
    - docker-containerd-shim
  tags: docker


- name: docker命令自动补全
  copy: src=docker dest=/etc/bash_completion.d/docker mode=0644

- name: docker国内镜像加速
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json

- name: flush-iptables
  shell: "iptables -F && iptables -X \
        && iptables -F -t nat && iptables -X -t nat \
        && iptables -F -t raw && iptables -X -t raw \
        && iptables -F -t mangle && iptables -X -t mangle"

- name: 创建docker的systemd unit文件
  template: src=docker.service.j2 dest=/etc/systemd/system/docker.service
  tags: upgrade,docker

- name: 开机启动 docker 服务
  shell: systemctl enable docker
  ignore_errors: true

- name: 启用 dockerd 服务
  shell: systemctl daemon-reload && systemctl restart docker
  tags: upgrade,docker

## 可选 ------安装docker查询镜像 tag的小工具----
# 需先安装轻量JSON处理程序‘jq’，已在 prepare 节点安装
- name: 安装 docker-tag
  copy: src=docker-tag dest={{ docker_bin_dir }}/docker-tag mode=0755


- include_tasks: docker-compose.yml
  when: docker_compose_install
  tags: [compose,download]

- include_tasks: docker-machine.yml
  when: docker_machine_install
  tags: [machine,download]